In [2]:
import numpy as np

In [3]:
np.arange(0,24,3).reshape(2,4)

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21]])

In [4]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [10]:
np.random.seed(101)
my_arr = np.random.randn(4,5)
my_arr

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795],
       [-0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206],
       [ 0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722],
       [ 0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [9]:
my_arr[:3, 1:4]

array([[ 0.62813271,  0.90796945,  0.50382575],
       [-0.84807698,  0.60596535, -2.01816824],
       [-0.58900053,  0.18869531, -0.75887206]])

In [9]:
my_arr[1:3,2:3]

array([[0.60596535],
       [0.18869531]])

In [10]:
arr = np.arange(0,100).reshape(4,5,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [11]:
arr[1][1:3,2:4]

array([[32, 33],
       [37, 38]])

In [12]:
np.random.seed(3)
np.random.randint(1,10)

9

In [13]:
my_arr.ndim

2

In [14]:
my_arr.shape

(4, 5)

In [15]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.sort(my_arr)

array([[ 0.50382575,  0.62813271,  0.65111795,  0.90796945,  2.70684984],
       [-2.01816824, -0.84807698, -0.31931804,  0.60596535,  0.74012206],
       [-0.93323722, -0.75887206, -0.58900053,  0.18869531,  0.52881349],
       [ 0.19079432,  0.68350889,  0.95505651,  1.97875732,  2.60596728]])

In [17]:
a1 = np.array(([1,2],[3,4]))

a2=np.array(([5,6],[7,8]))

In [18]:
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [19]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
np.hsplit(my_arr,(3,2))

[array([[ 2.70684984,  0.62813271,  0.90796945],
        [-0.31931804, -0.84807698,  0.60596535],
        [ 0.52881349, -0.58900053,  0.18869531],
        [ 0.95505651,  0.19079432,  1.97875732]]),
 array([], shape=(4, 0), dtype=float64),
 array([[ 0.90796945,  0.50382575,  0.65111795],
        [ 0.60596535, -2.01816824,  0.74012206],
        [ 0.18869531, -0.75887206, -0.93323722],
        [ 1.97875732,  2.60596728,  0.68350889]])]

In [21]:
arr3 = np.arange(0,100)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
arr3[arr3 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [23]:
arr3[arr3 % 2 == 0].std()

np.float64(28.861739379323623)

In [24]:
arr3[arr3 % 2 == 0].var()

np.float64(833.0)

In [25]:
arr3[arr3 % 2 == 0].mean()

np.float64(49.0)

In [26]:
arr3[arr3 % 2 == 0].sum()

np.int64(2450)

In [27]:
arr3[arr3 % 2 == 0] / 2

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [28]:
arr3[arr3 % 2 == 0] + 10

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108])

In [29]:
import pandas as pd

In [30]:
ser = pd.Series(['A','B','C'])
ser

0    A
1    B
2    C
dtype: object

In [31]:
df0 = pd.DataFrame(np.arange(0,20).reshape(4,5), index=[1,2,3,4], columns=['A','B','C','D','E'])
df0

A   B   C   D   E
1   0   1   2   3   4
2   5   6   7   8   9
3  10  11  12  13  14
4  15  16  17  18  19

In [32]:
df1 = pd.DataFrame(np.random.randn(4,5), columns=['A','B','C','D','E'] )
df1

A         B         C         D         E
0 -1.029471  1.024807  0.980554  0.027019 -0.460042
1 -0.057921  2.077574 -0.601312  0.939236 -1.180409
2 -0.347330  0.066299 -1.627585  0.397886 -1.629157
3 -0.638936 -0.560810  1.818983  0.156573 -1.203276

In [33]:
df1["New"] = df1["A"] + df1["B"]

In [34]:
df1

A         B         C         D         E       New
0 -1.029471  1.024807  0.980554  0.027019 -0.460042 -0.004665
1 -0.057921  2.077574 -0.601312  0.939236 -1.180409  2.019653
2 -0.347330  0.066299 -1.627585  0.397886 -1.629157 -0.281031
3 -0.638936 -0.560810  1.818983  0.156573 -1.203276 -1.199745

In [35]:
df1.drop("New", axis=1, inplace=True)

In [36]:
df1

A         B         C         D         E
0 -1.029471  1.024807  0.980554  0.027019 -0.460042
1 -0.057921  2.077574 -0.601312  0.939236 -1.180409
2 -0.347330  0.066299 -1.627585  0.397886 -1.629157
3 -0.638936 -0.560810  1.818983  0.156573 -1.203276

In [37]:
df1[["C","D"]]

C         D
0  0.980554  0.027019
1 -0.601312  0.939236
2 -1.627585  0.397886
3  1.818983  0.156573

In [38]:
df1.loc[2]

A   -0.347330
B    0.066299
C   -1.627585
D    0.397886
E   -1.629157
Name: 2, dtype: float64

In [39]:
df1

A         B         C         D         E
0 -1.029471  1.024807  0.980554  0.027019 -0.460042
1 -0.057921  2.077574 -0.601312  0.939236 -1.180409
2 -0.347330  0.066299 -1.627585  0.397886 -1.629157
3 -0.638936 -0.560810  1.818983  0.156573 -1.203276

In [40]:
df1.loc[[1,2],["B","C"]]

B         C
1  2.077574 -0.601312
2  0.066299 -1.627585

In [41]:
df1[(df1["C"] > 0) | (df1["D"] > 0)]

A         B         C         D         E
0 -1.029471  1.024807  0.980554  0.027019 -0.460042
1 -0.057921  2.077574 -0.601312  0.939236 -1.180409
2 -0.347330  0.066299 -1.627585  0.397886 -1.629157
3 -0.638936 -0.560810  1.818983  0.156573 -1.203276

In [42]:
df1["New"] = ['a','b','c','d']
df1

A         B         C         D         E New
0 -1.029471  1.024807  0.980554  0.027019 -0.460042   a
1 -0.057921  2.077574 -0.601312  0.939236 -1.180409   b
2 -0.347330  0.066299 -1.627585  0.397886 -1.629157   c
3 -0.638936 -0.560810  1.818983  0.156573 -1.203276   d

In [43]:
df1.set_index("New")

A         B         C         D         E
New                                                  
a   -1.029471  1.024807  0.980554  0.027019 -0.460042
b   -0.057921  2.077574 -0.601312  0.939236 -1.180409
c   -0.347330  0.066299 -1.627585  0.397886 -1.629157
d   -0.638936 -0.560810  1.818983  0.156573 -1.203276